### ISSUE TITLE
question 7

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/phase-3-quiz-sinatra#8]
question 7 has no space to answer it

**Comment by lizbur10** [comment]
Hi @belam170 - so sorry for the inconvenience! I am not able to recreate this problem - the question is structured properly in the blueprint. It's possible the problem is just in your Canvas course. If you can send me a link to the quiz, I'll be happy to take a look.

Thanks for contributing to the curriculum 💙

**Comment by ghost** [comment]
https://moringa.instructure.com/courses/302/quizzes/5886?module_item_id=55810
